# Generated by Django 5.2.4 on 2025-07-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
