# Generated by Django 5.2.4 on 2025-07-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_status_alter_product_id'),
        ('products', '0005_alter_product_supplier'),
    ]

    operations = [
    ]
