# Generated by Django 5.2.3 on 2025-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20250722_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Defective', 'Defective'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
